import { Button, Text, useColorModeValue } from "@chakra-ui/react";
import type { NextPage } from "next";
import "@fontsource/rubik-mono-one";
import Typical from "react-typical";
import Image from "next/image";
import { BiChevronDown } from "react-icons/bi";
import { useEffect, useRef } from "react";
import Aos from "aos";
import "aos/dist/aos.css";
import LandingLayout from "../components/LandingLayout";
import { auth } from "../firebase";
import Link from "next/link";
import Head from "next/head";

const Home: NextPage = () => {
  const belowSectionRef = useRef<HTMLDivElement>(null);
  const handleBelowPitchClick = () => {
    belowSectionRef.current?.scrollIntoView({ behavior: "smooth" });
  };
  useEffect(() => {
    Aos.init({
      once: true,
    });
  });
  return (
    <LandingLayout>
      <Head>
        <title>Home | Compifly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex flex-col items-center">
        {/* PITCH SECTION */}
        <div className="w-full relative">
          <div className="h-[210vh] bg-violet-600 absolute z-[-1] skew-y-2 w-full -translate-y-[100vh]" />
          <div className="h-[210vh] bg-pink-600 absolute z-[-3] skew-y-3 w-full -translate-y-[99vh]" />
          <div className="h-[210vh] bg-teal-600 absolute z-[-4] skew-y-[3.5deg] w-full -translate-y-[98.5vh]" />

          <div
            className={`w-full  h-screen flex justify-center md:justify-start text-center md:text-start items-center p-4 py-[12rem]`}
          >
            <div className="w-full lg:w-2/3 text-2xl md:text-3xl lg:text-4xl xl:text-5xl flex flex-col items-center">
              <Text className="leading-snug text-center" color="white">
                A social media app for
              </Text>
              <div
                className={`w-full flex justify-center font-extrabold ${useColorModeValue(
                  "text-green-300",
                  "text-green-400"
                )}`}
              >
                <Typical
                  steps={["Competitive Programmers", 1000]}
                  loop={Infinity}
                  wrapper="p"
                />
              </div>
              <span className="my-8" />
              {!auth.currentUser ? (
                <Link href="/register">
                  <Button
                    className="w-full max-w-sm p-2"
                    height="14"
                    bgColor="green.400"
                    color="white"
                    fontWeight="bold"
                  >
                    GET STARTED
                  </Button>
                </Link>
              ) : (
                <></>
              )}
            </div>
            <div className="hidden lg:flex md:h-[20rem] md:w-[20rem] lg:h-[30rem] lg:w-[30rem] xl:h-[35rem] xl:w-[35rem] 2xl:h-[45rem] 2xl:w-[45rem] absolute  right-[2rem] top-[10rem] 2xl:top-[5rem]">
              <Image src="/logo-art.png" alt="" layout="fill" />
            </div>
          </div>
        </div>
        <div className="my-20" />
        <div className="w-full min-h-screen flex flex-col justify-center px-4 md:px-28 py-2">
          <div className="w-full flex flex-col justify-center items-center">
            <Text className="text-base md:text-lg lg:text-xl font-semibold">
              What can I do here?
            </Text>
          </div>
          <div className="my-10" />

          <div className="flex flex-col md:flex-row">
            {/* PROFILE SECTION */}
            <div className="w-full flex flex-col items-center p-8">
              <div
                className="h-[16rem] w-[16rem]"
                data-aos="fade-up"
                data-aos-duration="800"
              >
                <Image src="/profile-intro.png" alt="" layout="fill" />
              </div>
              <span className="my-4" />
              <Text
                className="leading-snug text-lg md:text-xl lg:text-2xl font-semibold"
                color="white"
              >
                {"Create Profile"}
              </Text>
              <span className="my-2" />
              <Text
                className="leading-snug text-base md:text-lg lg:text-xl opacity-80 text-center"
                color="white"
              >
                {
                  "Create your profile and showcase your competitive 🦾 prowess through badges."
                }
              </Text>
            </div>
            {/* FRIEND SECTION */}
            <div className="my-6" />
            <div className="w-full flex flex-col items-center p-8">
              <div
                className="h-[16rem] w-[16rem]"
                data-aos="fade-up"
                data-aos-duration="800"
              >
                <Image src="/friend-intro.png" alt="" layout="fill" />
              </div>
              <span className="my-4" />
              <Text
                className="leading-snug text-lg md:text-xl lg:text-2xl font-semibold"
                color="white"
              >
                {"Add Friends"}
              </Text>
              <span className="my-2" />
              <Text
                className="leading-snug text-base md:text-lg lg:text-xl opacity-80 text-center"
                color="white"
              >
                {
                  "View others profile, see their ratings and title and add them as friends."
                }
              </Text>
            </div>
            {/* RANKING SECTION */}
            <div className="my-6" />
            <div className="w-full flex flex-col items-center p-8">
              <div
                className="h-[16rem] w-[16rem]"
                data-aos="fade-up"
                data-aos-duration="800"
              >
                <Image src="/ranking-intro.png" alt="" layout="fill" />
              </div>
              <span className="my-4" />
              <Text
                className="leading-snug text-lg md:text-xl lg:text-2xl font-semibold"
                color="white"
              >
                {"See Rankings"}
              </Text>
              <span className="my-2" />
              <Text
                className="leading-snug text-base md:text-lg lg:text-xl opacity-80 text-center"
                color="white"
              >
                {
                  "See ranking among your friends and show them who's the alpha."
                }
              </Text>
            </div>
            <div className="my-6" />
          </div>
        </div>
      </div>
    </LandingLayout>
  );
};

export default Home;
