import { Avatar, Heading, Text } from "@chakra-ui/react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Layout from "../components/Layout";
import LoadingLayout from "../components/LoadingLayout";
import { auth } from "../firebase";
import useDB from "../hooks/useDB";

const Home: NextPage = () => {
  const router = useRouter();
  const { userDocExists } = useDB();
  const [authLoading, setAuthLoading] = useState<boolean>(false);

  useEffect(() => {
    const checkUser = async () => {
      setAuthLoading(true);
      if (auth.currentUser?.uid) {
        if (!(await userDocExists(auth.currentUser.uid)))
          router.replace("/create_user");
      } else router.replace("/login");
      setAuthLoading(false);
    };

    checkUser();

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [auth.currentUser]);

  if (authLoading) return <LoadingLayout />;

  return (
    <Layout>
      <div className="w-full h-full flex flex-col justify-center items-center">
        <Head>
          <title>Complify</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Heading className="">Hello</Heading>
        <span className="my-2" />
        <Avatar src={auth.currentUser?.photoURL || ""} size="xl" />
        <span className="my-2" />
        <Text>{auth.currentUser?.displayName}</Text>
      </div>
    </Layout>
  );
};

export default Home;
